// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEymnHdxHURyNh6UNPKdaMyACkUL1Sr1s',
    appId: '1:324187337332:web:c8b1c5999c120ab8285721',
    messagingSenderId: '324187337332',
    projectId: 'musikat-app',
    authDomain: 'musikat-app.firebaseapp.com',
    databaseURL: 'https://musikat-app-default-rtdb.firebaseio.com',
    storageBucket: 'musikat-app.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAf59vJzSrhUoRQ7t6RVkHlV9Fxu04n34',
    appId: '1:324187337332:ios:7e0b01e48db33349285721',
    messagingSenderId: '324187337332',
    projectId: 'musikat-app',
    databaseURL: 'https://musikat-app-default-rtdb.firebaseio.com',
    storageBucket: 'musikat-app.appspot.com',
    androidClientId: '324187337332-jf6ibpb5cj5ger85u77m157j5r1oqppv.apps.googleusercontent.com',
    iosClientId: '324187337332-co20kc04g777rkmnf87abmfjm38huhpk.apps.googleusercontent.com',
    iosBundleId: 'com.example.musikatWebAdmin.RunnerTests',
  );
}
